//! Live readings; missing guest statistics stay optional rather than becoming zeroes.
use std::{
    collections::HashMap,
    sync::Mutex,
    time::{Instant, SystemTime, UNIX_EPOCH},
};

use serde::Serialize;
use virt::{connect::Connect, error::ErrorNumber};

#[derive(Serialize)]
pub struct FilesystemUsage {
    pub mountpoint: String,
    pub used_bytes: u64,
    pub total_bytes: u64,
}

#[derive(Serialize)]
pub struct InstanceStatus {
    pub state: String,
    pub active: bool,
    pub cpu_percent: Option<f64>,
    pub vcpus: u32,
    pub memory_used_bytes: Option<u64>,
    pub memory_total_bytes: Option<u64>,
    pub memory_allocated_bytes: u64,
    pub disk_capacity_bytes: Option<u64>,
    pub disk_allocated_bytes: Option<u64>,
    pub filesystems: Option<Vec<FilesystemUsage>>,
}

struct CpuSample {
    at: Instant,
    cpu_time: u64,
    vcpus: u32,
}

#[derive(Default)]
pub struct Metrics {
    samples: Mutex<HashMap<String, CpuSample>>,
}

impl Metrics {
    pub fn forget(&self, id: &str) {
        self.samples.lock().unwrap().remove(id);
    }

    pub fn read(&self, qemu: &Connect, id: &str) -> anyhow::Result<InstanceStatus> {
        let domain = match super::lookup_domain(qemu, id) {
            Ok(domain) => domain,
            Err(error) if error.code() == ErrorNumber::NoDomain => {
                self.forget(id);
                return Ok(InstanceStatus {
                    state: "missing".into(),
                    active: false,
                    cpu_percent: None,
                    vcpus: 0,
                    memory_used_bytes: None,
                    memory_total_bytes: None,
                    memory_allocated_bytes: 0,
                    disk_capacity_bytes: None,
                    disk_allocated_bytes: None,
                    filesystems: None,
                });
            }
            Err(error) => return Err(error.into()),
        };
        let info = domain.get_info()?;
        let active = domain.is_active()?;
        let state = super::state_label(info.state).to_string();
        let cpu_percent = if active {
            let now = Instant::now();
            let previous = self.samples.lock().unwrap().insert(
                id.into(),
                CpuSample {
                    at: now,
                    cpu_time: info.cpu_time,
                    vcpus: info.nr_virt_cpu,
                },
            );
            previous.and_then(|previous| {
                let elapsed = now.duration_since(previous.at).as_secs_f64();
                if !(0.5..=30.0).contains(&elapsed)
                    || info.nr_virt_cpu == 0
                    || previous.vcpus != info.nr_virt_cpu
                {
                    return None;
                }
                info.cpu_time.checked_sub(previous.cpu_time).map(|delta| {
                    (delta as f64 / 1e9 / elapsed / f64::from(info.nr_virt_cpu) * 100.0)
                        .clamp(0.0, 100.0)
                })
            })
        } else {
            self.forget(id);
            Some(0.0)
        };
        let mut status = InstanceStatus {
            state,
            active,
            cpu_percent,
            vcpus: info.nr_virt_cpu,
            memory_used_bytes: None,
            memory_total_bytes: None,
            memory_allocated_bytes: if active {
                info.memory * 1024
            } else {
                info.max_mem * 1024
            },
            disk_capacity_bytes: None,
            disk_allocated_bytes: None,
            filesystems: None,
        };
        // sdb is the managed disk target generated by this application.
        if let Ok(block) = domain.get_block_info("sdb", 0) {
            status.disk_capacity_bytes = Some(block.capacity);
            status.disk_allocated_bytes = Some(block.allocation);
        }
        if active {
            // Enables guest balloon statistics for existing as well as newly created guests.
            // A driver may not support this; other metrics must still remain available.
            let _ = domain.set_memory_stats_period(5, 1); // VIR_DOMAIN_AFFECT_LIVE
            if let Ok(stats) = domain.memory_stats(0) {
                let value = |tag| {
                    stats
                        .iter()
                        .find(|stat| stat.tag == tag)
                        .map(|stat| stat.val)
                };
                let now = SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs();
                // Libvirt tags: AVAILABLE=5, USABLE=8, LAST_UPDATE=9; all memory values are KiB.
                if value(9).is_some_and(|timestamp| timestamp > 0 && now.abs_diff(timestamp) <= 30)
                    && let (Some(total), Some(usable)) = (value(5), value(8))
                    && usable <= total
                {
                    status.memory_total_bytes = Some(total * 1024);
                    status.memory_used_bytes = Some((total - usable) * 1024);
                }
            }
            // No guest commands are executed: this is the read-only guest-agent filesystem query.
            if let Ok(reply) = domain.qemu_agent_command(r#"{"execute":"guest-get-fsinfo"}"#, 2, 0)
                && let Ok(reply) = serde_json::from_str::<serde_json::Value>(&reply)
                && let Some(filesystems) = reply.get("return").and_then(|value| value.as_array())
            {
                status.filesystems = Some(
                    filesystems
                        .iter()
                        .filter_map(|fs| {
                            Some(FilesystemUsage {
                                mountpoint: fs.get("mountpoint")?.as_str()?.into(),
                                used_bytes: fs.get("used-bytes")?.as_u64()?,
                                total_bytes: fs.get("total-bytes")?.as_u64()?,
                            })
                        })
                        .collect(),
                );
            }
        }
        Ok(status)
    }
}
